version: 2.1

jobs:
  build_and_test:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run:
          name: Prepare Build
          command: ./.circleci/prepare_build.sh
      - run:
          name: chmod install script
          command: chmod +x install_dependencies.sh
      - run:
          name: run install script
          command: ./install_dependencies.sh

      - run:
          name: compile
          command: |
            mkdir build
            cd build
            cmake -DROCK_TEST_ENABLED=ON ..
            make -j4 install
      - run:
          name: Run C++ Tests
          command: make cpp_test
      - run:
          name: Run Python Tests
          command: make pytest

workflows:
  build_and_test_workflow:
    jobs:
      - build_and_test
