#include <pybind11/pybind11.h>
#include <pybind11_json/pybind11_json.hpp>

namespace py = pybind11;


void PYBIND11_INIT_XTYPES_GENERATOR__ENUMS(py::module_ &);
void PYBIND11_INIT_XTYPES_GENERATOR__STRUCTS(py::module_ &);
void PYBIND11_INIT_XTYPES_GENERATOR__UTILS(py::module_ &);
void PYBIND11_INIT_XTYPES_GENERATOR__REGISTRY(py::module_ &);

PYBIND11_EXPORT
void PYBIND11_INIT_XTYPES_GENERATOR__CUSTOM_BINDS(py::module_& m) {
  PYBIND11_INIT_XTYPES_GENERATOR__ENUMS(m);
  PYBIND11_INIT_XTYPES_GENERATOR__STRUCTS(m);
  PYBIND11_INIT_XTYPES_GENERATOR__UTILS(m);
  PYBIND11_INIT_XTYPES_GENERATOR__REGISTRY(m);
}
